version = 0.1

[default.deploy]
stack_name = "p6-template-sam-eslint-pnpm-ts-flatfile"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"

[default.package]
s3_bucket = "p6-DNE-CHANGE-ME"
output_template_file = "template-output.yaml"
