name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: p6m7g8-actions/checkout@main

      - name: Install Node.js
        uses: p6m7g8-actions/node-setup@main

      - name: Run build
        run: pnpm run ci
